version: '3.8'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - PORT=${PORT}
    depends_on:
      - warehouse

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - BASE_URL=${BASE_URL}
    depends_on:
      - backend

  warehouse:
    container_name: warehouse
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: tracker
    volumes:
      - ./database/run_script.sh:/docker-entrypoint-initdb.d/run_script.sh
      - ./database/migrations:/sql/migrations
      - ./database/seeds/cashflow:/sql/seeds
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
volumes:
  postgres-data:
